config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions', users: 'users', passwords: 'users/passwords' }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  resources :users, only: [:index, :show]
  get '/terms', to: 'pages#terms'
	root 'pages#home'

  namespace :reviews do 
    resources :picks, only: :index, defaults: { format: :json }
  end
  namespace :products do 
    get 'search', to: 'products#search'
  end
  resources :brands do
	  post :import, on: :collection
	end
  resources :products do
    post :import, on: :collection
  end
  resources :reviews
  post 'compare/:id' => 'compares#create', as: 'create_compare'
  delete 'compare/:id' => 'compares#destroy', as: 'destroy_compare'
  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products, dependent: :destroy
  has_one_attached :image, dependent: :destroy
  validates :name, presence: true, uniqueness: { case_sensitive: false },
                   length: { maximum: 50 }
  validates :image, content_type: { in: %w[image/jpeg image/gif image/png],
                                    message: "must be a valid image format" },
                    size: { less_than: 5.megabytes,
                            message: "should be less than 5MB" }

  def self.csv_attributes
    ["name"]
  end

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      brand = new
      brand.attributes = row.to_hash.slice(*csv_attributes)
      begin
        brand.save!
      rescue StandardError => e
        puts e.class
      end
    end
  end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit destroy]
  before_action :admin_user, only: %i[new create edit update destroy import]
  before_action :set_brand, only: %i[show destroy edit update]
  include Pagy::Backend

  def new
    @brand = Brand.new
  end

  def create
    @brand = Brand.new(brand_params)
    if @brand.save
      flash[:success] = "Add Brand Successfully"
      redirect_to @brand
    else
      flash.now[:danger] = "Add Brand is failed"
      render 'new'
    end
  end

  def index
    @pagy, @brands = pagy(Brand.with_attached_image.all)
  end

  def show; end

  def destroy
    if @brand.destroy
      flash[:success] = "Brand is deleted"
      redirect_to brands_path
    elsif current_user.admin?
      flash.now[:danger] = "Fail to delete Brand"
      render 'edit'
    else
      flash[:alert] = "Prohibit to Access This Page"
      redirect_to request.referrer || root_url
    end
  end

  def edit; end

  def update
    if @brand.update(brand_params)
      flash[:success] = "Brand is updated"
      redirect_to @brand
    else
      flash.now[:danger] = "Updating is faild"
      render 'edit'
    end
  end

  def import
    redirect_to brands_path, notice: "Import is Succeeded" if Brand.import(params[:file])
  end

  private

  def brand_params
    params.require(:brand).permit(:name, :image)
  end

  def set_brand
    @brand = Brand.find(params[:id])
  rescue ActiveRecord::RecordNotFound => e
    puts e
    flash[:danger] = "入力したブランドは存在しません"
    redirect_to request.referrer || brands_path
  rescue StandardError => e
    puts e
  end
end

app/helpers/brands_helper.rb
module BrandsHelper
  def logo_image_default(brand)
    if brand.image.attached?
      link_to image_tag(brand.image, width: "75px",
                                     class: "img-fluid"), brand_path(brand)
    else
      link_to image_pack_tag("brand_default_logo.png",
                             width: "75px", class: "img-fluid"), brand_path(brand)
    end
  end
end

app/views/brands/_brand.html.slim
li id = "brand-#{brand.id}"
  .card.col-12.my-1.p-2
    .row
      .col-4.col-md-4
        = logo_image_default(brand)
      .col-8.col-md-8
        p = link_to brand.name, brand
        p = link_to "登録製品: #{brand.products.count}", brand, class: "count--text"
    - if user_signed_in? && current_user.admin?
      .row
        .col-12
          = link_to edit_brand_path(brand), class: "edit_link" do
            i.fas.fa-pencil-alt.fa-xs.pull-right

app/views/brands/_product.html.slim
li.card.mb-1 id = "product-#{product.id}"
  .row.p-1
    .col-4
      = product_image_default(product)
    .col-8
      .d-flex
        p = link_to product.name, product
        - if user_signed_in? && current_user.admin?
          = link_to edit_product_path(product), class: "edit_link px-2" do
            i.fas.fa-pencil-alt.fa-xs.pull-right
      p = link_to "レビュー数: #{product.reviews.count}", product, class: "count--text"

app/views/brands/edit.html.slim
- provide(:title, "Edit Brand")

h1 Edit a New Brand
.container
  .row
    .col-12.col-md-6.col-md-offset-3.card.text-center.py-3
      = form_with(model: @brand, local: true) do |f|
        = render 'shared/error_messages', object: f.object
        h3.mb-2 = f.label :name, class: "col-12 col-md-12"
        = f.text_field :name, class: "col-12 col-md-12 form-control mb-2"
        
        = f.file_field :image, class: "col-12 col-md-12 form-control mb-2", accept: "image/jpeg,image/gif,image/png"
        
        = f.submit "Update Brand", class: "btn btn-primary col-12 col-md-12 form-control mb-2"
      
      = link_to @brand, method: :delete, data:{confirm: 'You sure?'}, class: 'd-grid delete_link' do
        button.btn.btn-outline-danger.mb-3 Delete
      
      // brand image_size varidation
      javascript:
        $("#brand_image").bind("change", function sizeVaridation() {
          const sizeInMegaBytes = this.files[0].size / 1024 / 1024;
          if (sizeInMegaBytes > 5) {
            alert("画像の容量は5MBまでです。他の画像を選択してください。");
            $("#brand_image").val("");
          }
        });

app/views/brands/index.html.slim
- provide(:title, 'ブランド一覧')
.container
  .row
    .col-12
      h2.text-center = yield(:title)

.container
  ol.brands.px-0
    .row
      .col-12.offset-md-1.col-md-10.offset-md-1.offset-lg-3.col-lg-6.offset-lg-3
        = render @brands
        = render 'shared/pagination_bar'

app/views/brands/new.html.slim
- provide(:title, 'Add Brand')

.container
  h1 Add a New Brand
.container
  .row.m-1
    .col-12.col-md-6.col-md-offset-3.card.text-center.py-3
      = form_with(model: @brand, local: true) do |f|
        = render 'shared/error_messages', object: f.object
        h3
          = f.label :name, class: "col-12 col-md-12 mb-2"
        = f.text_field :name, class: "col-12 col-md-12 mb-2"
        
        = f.file_field :image, class: "col-12 col-md-12 form-control mb-2", accept: "image/jpeg,image/gif,image/png"

        .g-grid
          = f.submit "Create a new brand", class: "btn btn-primary col-12 col-md-12"
  .row
    .col-12.col-md-6.col-md-offset-3.card.text-center.py-3
      h3 CSV form
      = form_tag import_brands_path, multipart: true, class: 'mb-2' do
        /= render 'shared/error_messages', object: f.object
        = file_field_tag :file , accept: 'text/csv'
        = submit_tag "Import", class: "btn btn-primary"

        // brand image_size varidation
        javascript:
          $("#brand_image").bind("change", function sizeVaridation() {
            const sizeInMegaBytes = this.files[0].size / 1024 / 1024;
            if (sizeInMegaBytes > 5) {
              alert("画像の容量は5MBまでです。他の画像を選択してください。");
              $("#brand_image").val("");
            }
          });

app/views/brands/show.html.slim
- provide(:title, @brand.name)
.container
  .row.p-2.brand_title
    .col-12.offset-md-1.col-md-10.offset-md-1.offset-lg-3.col-lg-6.offset-lg-3
      .row.p-2
        .col-3
          .logo--frame
            = logo_image_default(@brand)
        .col-9.d-flex.mt-3
          h2 = @brand.name
          - if user_signed_in? && current_user.admin?
            = link_to edit_brand_path(@brand), class: "edit_link px-2" do
              i.fas.fa-pencil-alt.fa-xs.pull-right
  .row
    .col-12.offset-md-1.col-md-10.offset-md-1.offset-lg-3.col-lg-6.offset-lg-3
      ol.products
        - @brand.products.with_attached_image.each do |product|
          = render 'brands/product', product: product