config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions', users: 'users', passwords: 'users/passwords' }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  resources :users, only: [:index, :show]
  get '/terms', to: 'pages#terms'
	root 'pages#home'

  namespace :reviews do 
    resources :picks, only: :index, defaults: { format: :json }
  end
  namespace :products do 
    get 'search', to: 'products#search'
  end
  resources :brands do
	  post :import, on: :collection
	end
  resources :products do
    post :import, on: :collection
  end
  resources :reviews
  post 'compare/:id' => 'compares#create', as: 'create_compare'
  delete 'compare/:id' => 'compares#destroy', as: 'destroy_compare'
  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :brand
  has_many :reviews, dependent: :destroy
  has_many :compares
  has_one_attached :image
  validates :brand_id, presence: true
  validates :name, presence: true, length: { in: 1..50 }
  validates :soc_antutu_score, presence: true,
                               numericality: { only_integer: true,
                                               greater_than_or_equal_to: 1 }
  validates :battery_capacity, presence: true,
                               numericality: { only_integer: true,
                                               greater_than_or_equal_to: 1 }
  validates :image, content_type: { in: %w[image/jpeg image/gif image/png],
                                    message: "must be a valid image format" },
                    size: { less_than: 5.megabytes,
                            message: "should be less than 5MB" }
  validates :release_date, presence: true

  def update_rate_average
    reviews_rate = reviews.average(:rate)
    reviews_rate ||= 0
    update!(rate_average: reviews_rate)
  end

  def self.csv_attributes
    %w[name brand_id soc_antutu_score battery_capacity release_date]
  end

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      product = new
      product.attributes = row.to_hash.slice(*csv_attributes)
      begin
        product.save!
      rescue StandardError => e
        puts e.class
      end
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, only: %i[index new create edit destroy search]
  before_action :admin_user, only: %i[new create edit update destroy]
  before_action :set_q, only: %i[index search]
  include Pagy::Backend

  def show
    if @product = Product.find(params[:id])
      @review = current_user.reviews.build if user_signed_in?
      @select_product_reviews = @product.reviews.includes(:user).with_attached_image
      @product_like_countup = Like.likes_count(params[:id])
      @products_for_compare = Compare.where('user_id=?', current_user.id).includes(product: [:brand, { image_attachment: :blob }]).all
    else
      flash[:danger] = '入力した製品は存在しません'
      redirect_to products_path
    end
  rescue ActiveRecord::RecordNotFound => e
    puts e
    @brands = Brand.all
    flash[:danger] = "入力した製品は存在しません"
    redirect_to request.referrer || root_path
  rescue StandardError => e
    puts e
  end

  def index
    @q = Product.with_attached_image.includes(:brand).ransack(params[:q])
    @pagy, @products = pagy(@q.result(distinct: true))
  end

  def edit
    @product = Product.find(params[:id])
    @brands = Brand.all
  rescue ActiveRecord::RecordNotFound => e
    puts e
    @brands = Brand.all
    flash[:danger] = "入力した製品は存在しません"
    redirect_to request.referrer || root_path
  rescue StandardError => e
    puts e
  end

  def new
    @product = Product.new
    @brands = Brand.all
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:success] = "Add Product Successfully"
      redirect_to @product
    else
      @brands = Brand.all
      flash.now[:danger] = "Fail to Add Product"
      render 'new'
    end
  rescue ActiveRecord::RecordNotUnique => e
    puts e
    @brands = Brand.all
    flash.now[:danger] = "Cannot add a same product as same brand"
    render 'new'
  rescue StandardError => e
    puts e
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:success] = "Product updated"
      redirect_to @product
    else
      @brands = Brand.all
      render 'edit'
      flash.now[:success] = "Fail to update"
    end
  end

  def destroy
    Product.find(params[:id]).destroy
    redirect_to products_path
  end

  def search
    @pagy, @results = pagy(@q.result.with_attached_image.includes(:brand))
  end

  def import
    redirect_to products_path, notice: "Import is Succeeded" if Product.import(params[:file])
  end

  private

  def product_params
    params.require(:product).permit(:name, :brand_id, :soc_antutu_score, :battery_capacity, :image, :release_date)
  end

  def set_q
    @q = Product.ransack(params[:q])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def average_rate(product)
    product.rate_average.zero? ? "-" : product.rate_average.floor(1)
  end

  def ranking_title
    return if params[:q].nil?

    sort_by = {
      'release_date asc' => '新発売',
      'release_date desc' => '新発売',
      'battery_capacity asc' => 'バッテリー容量',
      'battery_capacity desc' => 'バッテリー容量',
      'soc_antutu_score asc' => 'Antutu',
      'soc_antutu_score desc' => 'Antutu',
      'rate_average asc' => 'レビュー平均',
      'rate_average desc' => 'レビュー平均'
    }
    sort_by[params[:q][:s]]
  end

  def star_indicator(product)
    if product.rate_average.zero?
      content_tag(:i, class: "fas fa-star mt-1")
    else
      product.rate_average.floor.times do
        content_tag(:i, class: "fas fa-star active_star mt-1")
      end
      # 0.5 means base value for half-star should be indicated
      if product.rate_average % 1 >= 0.5
        content_tag(:i, class: "fas fa-star-half-alt active_star mt-1")
      end
      # 5 means max value of rating
      (5 - product.rate_average.round).times do
        content_tag(:i, class: "far fa-star no_active_star mt-1")
      end
    end
  end
end

app/views/products/_average_star_indicator.html.slim
- product.rate_average.floor.times do
  i.fas.fa-star.active_star.mt-1
/ 0.5 means base value for half-star should be indicated
- if product.rate_average % 1 >= 0.5
  i.fas.fa-star-half-alt.active_star_half.mt-1
/ 5 means max value of rating
- (5 - product.rate_average.round).times do
  i.far.fa-star.no_active_star.mt-1

app/views/products/_bookmark.html.slim
- if user_signed_in?
  - if current_user.marked_by?(product)
    = link_to destroy_compare_path(product), method: :DELETE, class: "btn btn-secondary", id: "release-compare-disable", local: true do
      i.fas.fa-bookmark

    javascript:
      $(function(){
        $('a#release-compare-disable').on('click',function(){
          $(this).click(function(){
            $(this).prop('disabled', true);
          });
        });
      });

  - else
    = link_to create_compare_path(product), method: :POST, class: "btn btn-outline-secondary", id: "compare-disable", local: true do
      i.far.fa-bookmark

    javascript:
      $(function(){
        $('a#compare-disable').on('click',function(){
          $(this).click(function(){
            $(this).prop('disabled', true);
          });
        });
      });

app/views/products/_delete.html.slim
- if current_user?(review.user)
  = link_to edit_review_path(review), class: "review_edit_link" do
    i.fas.fa-pencil-alt.fa-xs.__no_active.mx-2
  = link_to review, method: :delete, data:{confirm: "You sure?"},
    class: "delete_link" do
    i.far.fa-trash-alt.fa-xs.__no_active

app/views/products/_dropdown_sort.html.slim
.dropdown
  button#dropdownMenuButton.btn.btn-light.dropdown-toggle aria-expanded="false" data-bs-toggle="dropdown" type="button" 
    i.fas.fa-sort.mx-1
    | #{ranking_title}
  ul.dropdown-menu.dropdown-menu-end aria-labelledby="dropdownMenuButton" 
    = sort_link(@q, :release_date, default_order: :desc, hide_indicator: true)
      li.dropdown-item 新発売
    = sort_link(@q, :soc_antutu_score, default_order: :desc, hide_indicator: true)
      li.dropdown-item Antutu
    = sort_link(@q, :rate_average, default_order: :desc, hide_indicator: true)
      li.dropdown-item レビュー平均
    = sort_link(@q, :battery_capacity, default_order: :desc, hide_indicator: true)
      li.dropdown-item バッテリー容量

app/views/products/_like.html.slim
- if user_signed_in?
  - if current_user.liked_by?(review.id)   
    = link_to destroy_like_path(review), method: :DELETE, class: "__active", id: "release-like-disable", remote: true do
      i.fas.fa-thumbs-up.fa-xs
      span class="each-like-countup"
        = review.likes.count
  - else 
    = link_to create_like_path(review), method: :POST, class: "__no_active", id: "like-disable", remote: true do
      i.far.fa-thumbs-up.fa-xs
      span class="each-like-countup"
        = review.likes.count
- else
  i.far.fa-thumbs-up.fa-xs.__no_active
  span class="each-like-countup __no_active"
    = review.likes.count

app/views/products/_product.html.slim
.card.mb-2
  .row.p-2
    .col-4
      = product_image_default(product)
    .col-8
      = link_to product.name, product
      br
      = link_to product.brand.name, product.brand, class: "count--text"
      br
      = link_to product do
        .d-flex.mt-1
          - unless params[:q].nil?
            - case params[:q][:s]
              - when "release_date asc"
                i.fas.fa-table.count--text
                p.count--text.px-1 = product.release_date.strftime("%Y/%m/%d")
              - when "release_date desc"
                i.fas.fa-table.count--text
                p.count--text.px-1 = product.release_date.strftime("%Y/%m/%d")
              - when "battery_capacity asc"
                i.fas.fa-battery-full.count--text
                p.count--text.px-1
                  | #{product.battery_capacity} mAh
              - when "battery_capacity desc"
                i.fas.fa-battery-full.count--text
                p.count--text.px-1
                  | #{product.battery_capacity} mAh
              - when "soc_antutu_score asc"
                i.fas.fa-tachometer-alt.count--text
                p.count--text.px-1
                  | #{product.soc_antutu_score}
              - when "soc_antutu_score desc" 
                i.fas.fa-tachometer-alt.count--text
                p.count--text.px-1
                  | #{product.soc_antutu_score}
              - when "rate_average desc"
                = render 'products/average_star_indicator', product: product
                - if product.rate_average.positive?
                  p.count--text.p-1
                    | #{average_rate(product)}
                - else
                  p.count--text.p-1 -
              - when "rate_average asc"
                = render 'products/average_star_indicator', product: product
                - if product.rate_average.positive?
                  p.count--text.p-1
                    | #{average_rate(product)}
                - else
                  p.count--text.p-1 -
              - else
                i.fas.fa-table.count--text
                p.count--text.px-1 = product.release_date.strftime("%Y/%m/%d")
  - if user_signed_in?
    .row
      .col-12
        - if user_signed_in? && current_user.admin?
          = link_to edit_product_path(product), class: "edit_link" do
            i.fas.fa-pencil-alt.fa-xs.float-right

app/views/products/_product_info.html.slim
.row
  .col-12
    .d-flex.my-2
      .d-flex.px-2.text-center
        i.fas.fa-table.mt-1
        .mx-2.release_date = "#{@product.release_date.strftime("%Y/%m/%d")}"
      .d-flex.px-2.text-center.info_review_rate
        = render 'products/average_star_indicator', product: @product
        .value_rate_avarage.mx-2 = "#{average_rate(@product)} / 5.0"
  .col-12
    .d-flex
      .d-flex.px-2.text-center
        i.far.fa-thumbs-up.mt-1
        p.like_count.mx-1.mb-0 = "#{@product_like_countup}"
      .d-flex.px-2.text-center
        i.far.fa-comments.mt-1
        p.review_count.mx-1.mb-0 = "#{@product.reviews.count}"
      .d-flex.px-2.text-center
        i.fas.fa-tachometer-alt.mt-1
        p.value_antutu.mx-1.mb-0 = "#{@product.soc_antutu_score}"
        = render 'pages/info_antutu'
      .d-flex.px-2.text-center
        i.fas.fa-battery-full.mt-1
        p.value_battery.mx-1.mb-0 = "#{@product.battery_capacity}mAh"
        = render 'pages/info_battery'

app/views/products/_review.html.slim
ol.reviews
  - @select_product_reviews.includes(user: [avatar_attachment: :blob]).each do |review|
    li id ="review-#{review.id}"
      .card.mb-2.px-3
        .row
          .col-3.pt-3
            = render 'user_avatar', review: review
          .col-9
            .card-body
              p.card-title
                = link_to review.user.name, review.user
              p.card-text.count--text
                = review.updated_at.strftime('%Y/%m/%d')
        .row
          .col-12.my-1
            span.rate
              = render 'reviews/each_review_star_indicator', review: review
        .row
          .col-12
            p = review.content
            = render 'reviews/posted_image', review: review
        .row
          .col-12.pb-2
            .float-start
              div id ="review-like-#{review.id}"
                = render 'like', review: review
            - if current_user == review.user
              .float-end
                = render 'delete', review: review

app/views/products/_search_form.html.slim
= search_form_for @q, url: products_path do |f| 
  / = f.label :name_cont, '製品名'
  .input-group.mb-3
    = f.search_field :name_cont, class: "col-9 form-control", placeholder: "製品名"
    = f.submit '検索', class: "col-3 btn btn-secondary", id: "button-addon2"

app/views/products/_user_avatar.html.slim
- if review.user.avatar.attached?
  = image_tag review.user.avatar.variant(resize:"60x60")
- else
  i.fa.fa-user-circle.fa-3x.user--default

app/views/products/edit.html.slim
- provide(:title, 'Edit Product')

.container
  .row
    .col-12
      h1 Edit Product
.container
  .row
    .col-12.col-md-6.col-md-offset-3.card.text-center.py-3
      = form_with(model: @product, local: true) do |f|
        = render 'shared/error_messages', object: f.object

        = f.label :name, class: "col-12 col-md-12"
        = f.text_field :name, class: "col-12 col-md-12 form-control"
        
        = f.label :brand, class: "col-12 col-md-12"
        = f.collection_select(:brand_id, @brands, :id, :name, {}, class: "col-12 col-md-12 form-control")

        = f.label :soc_antutu_score, class: "col-12 col-md-12"
        = f.number_field :soc_antutu_score, class: "col-12 col-md-12 form-control"

        = f.label :battery_capacity, class: "col-12 col-md-12"
        = f.number_field :battery_capacity, class: "col-12 col-md-12 form-control"

        = f.label :release_date, class: "col-12 col-md-12"
        = f.datetime_field :release_date, class: "col-12 col-md-12", value: Time.current.strftime('%Y-%m-%dT00:00:00')
        
        = f.file_field :image, class: "col-12 col-md-12 form-control mb-2", accept: "image/jpeg,image/gif,image/png"
        
        = f.submit "Update Product", class: "btn btn-primary my-1 d-grid col-12 col-md-12"
        
      = link_to @product, method: :delete, data:{confirm: 'You sure?'}, class: 'd-grid delete_link' do
        button.btn.btn-outline-danger.mb-3 Delete

      / Image size Varidation
      javascript:
        $("#product_image").on("change", function sizeVaridation() {
          const sizeInMegaBytes = this.files[0].size / 1024 / 1024;
          if (sizeInMegaBytes > 5) {
            alert("画像の容量は5MBまでです。他の画像を選択してください。");
            $("#product_image").val("");
          }
        });
      

app/views/products/index.html.slim
- provide(:title, '製品一覧')

.container
  .row
    .col-12.offset-md-1.col-md-10.offset-md-1.offset-lg-3.col-lg-6.offset-lg-3
      h2.text-center.mt-2 = yield(:title)
.container
  .row
    .col-12.offset-md-1.col-md-10.offset-md-1.offset-lg-3.col-lg-6.offset-lg-3
      = render 'products/search_form'
  .row
    .col-12.offset-md-1.col-md-10.offset-md-1.offset-lg-3.col-lg-6.offset-lg-3.my-3
      .float-end = render 'products/dropdown_sort'
  .row
    .col-12.offset-md-1.col-md-10.offset-md-1.offset-lg-3.col-lg-6.offset-lg-3.mb-3
      ol.products
        .row
          .col-12
            - if @products.empty?
              p.text-center 該当商品 なし
            - else
              ol
                p.float-start
                  | #{@pagy.vars[:count]}件
        .row
          .col-12
            - @products.each.with_index(1) do |product, ranking_index|
              li id = "#{ranking_index}"
                = render 'products/product', product: product
            = render 'shared/pagination_bar'

app/views/products/new.html.slim
- provide(:title, 'Add Product')

.container
  .row
    .col-12
      h1 Add New Product
.container
  .row
    .col-12.col-md-6.col-md-offset-3.card.text-center.py-3
      = form_with(model: @product, local: true) do |f|
        = render 'shared/error_messages', object: f.object

        = f.label :name, class: "col-12 col-md-12"
        = f.text_field :name, class: "col-12 col-md-12"
        
        = f.label :brand, class: "col-12 col-md-12"
        = f.collection_select(:brand_id, @brands, :id, :name, {}, class: "col-12 col-md-12")

        = f.label :soc_antutu_score, class: "col-12 col-md-12"
        = f.number_field :soc_antutu_score, class: "col-12 col-md-12"

        = f.label :battery_capacity, class: "col-12 col-md-12"
        = f.number_field :battery_capacity, class: "col-12 col-md-12"

        = f.label :release_date, class: "col-12 col-md-12"
        = f.datetime_field :release_date, class: "col-12 col-md-12", value: Time.current.strftime('%Y-%m-%dT00:00:00')
        
        = f.file_field :image, class: "col-12 col-md-12 form-control mb-2", accept: "image/jpeg,image/gif,image/png"
        
        = f.submit "Create New Product", class: "btn btn-primary"

  .row
    .col-12.col-md-6.col-md-offset-3.card.text-center.py-3
      h3 CSV form
      = form_tag import_brands_path, multipart: true, class: 'mb-2' do
        /= render 'shared/error_messages', object: f.object
        = file_field_tag :file , accept: 'text/csv'
        = submit_tag "Import", class: "btn btn-primary"

      / Image size Varidation
      javascript:
        $("#product_image").on("change", function sizeVaridation() {
          const sizeInMegaBytes = this.files[0].size / 1024 / 1024;
          if (sizeInMegaBytes > 5) {
            alert("画像の容量は5MBまでです。他の画像を選択してください。");
            $("#product_image").val("");
          }
        });

app/views/products/search.html.slim
.container
  .row
    .col-12
      h2 Search Result
.container
  .row
    .col-12.pb-1
      = render 'products/search_form'
.products
  .container
    .row
      - if @results.empty?
        p No Results in All Products
      - else
        ol
          p = pluralize(@pagy.vars[:count] , "result")
          - @results.each do |product|
            li id = "#{product.id}"
              = render 'products/product', product: product
          = render 'shared/pagination_bar'