config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions', users: 'users', passwords: 'users/passwords' }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  resources :users, only: [:index, :show]
  get '/terms', to: 'pages#terms'
	root 'pages#home'

  namespace :reviews do 
    resources :picks, only: :index, defaults: { format: :json }
  end
  namespace :products do 
    get 'search', to: 'products#search'
  end
  resources :brands do
	  post :import, on: :collection
	end
  resources :products do
    post :import, on: :collection
  end
  resources :reviews
  post 'compare/:id' => 'compares#create', as: 'create_compare'
  delete 'compare/:id' => 'compares#destroy', as: 'destroy_compare'
  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'
end

app/views/layouts/_google_analytics.html.slim
script async="" src="https://www.googletagmanager.com/gtag/js?id=G-1DKE10TM22"

javascript:
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-1DKE10TM22');

app/views/layouts/_header.html.slim
header
  .container-fluid.g-0.bg-light.navbar-light.navbar-expand-lg
    .row.g-0
      .col-3.col-lg-8.order-lg-1
        button.navbar-toggler aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label=("Toggle navigation") data-bs-target="#navbarNavAltMarkup" data-bs-toggle="collapse" type="button" 
          span.navbar-toggler-icon
        #navbarNavAltMarkup.collapse.navbar-collapse
          .navbar-nav
            = link_to 'ホーム', root_path, class: "nav-link header--link"
            / = link_to 'Contact', contact_path, class: "nav-link"
            = link_to 'ブランド一覧', brands_path, class: "nav-link header--link"
            = link_to '製品一覧', products_path, class: "nav-link header--link"
      .col-6.col-lg-2.order-lg-0
        nav.navbar-light.bg-light
          .container.d-flex.align-items-center
            a.navbar-brand
              = link_to image_pack_tag("smar_logo.png", alt: "Sma-R logo", length:"40px"), root_url
              = link_to "Sma-R", root_url
      .col-3.col-lg-2.order-lg-2
        = render 'layouts/profile-dropdown'

app/views/layouts/_profile-dropdown.html.slim
- if user_signed_in?
  .dropdown.float-end
    button#dropdownMenuButton1.btn.btn-light.dropdown-toggle aria-expanded="false" data-bs-toggle="dropdown" type="button" 
      - if current_user.avatar.attached?
        = image_tag current_user.avatar.variant(resize:"35x35")
      - else
        i.fas.fa-user-circle.fa-2x.user--default
    ul.dropdown-menu aria-labelledby="dropdownMenuButton1" 
      = link_to user_path(current_user), class: "dropdown-item"
        li プロフィール
      = link_to destroy_user_session_path, method: :delete, class: "dropdown-item"
        li ログアウト
- else
  .dropdown.float-end
    button#dropdownMenuButton1.btn.btn-light.dropdown-toggle aria-expanded="false" data-bs-toggle="dropdown" type="button" 
      i.fa.fa-user-circle.fa-2x.user--default
    ul.dropdown-menu.dropdown-menu-right aria-labelledby="dropdownMenuButton1" 
      = link_to new_user_session_path, class: "dropdown-item"
        li ログイン
      = link_to users_guest_sign_in_path, method: :post, class: "dropdown-item"
        li ゲストログイン
      = link_to new_user_registration_path, class: "dropdown-item"
        li 新規登録

app/views/layouts/_rails_default.html.slim
meta[name="viewport" content="width=device-width,initial-scale=1"]
= csrf_meta_tags
= csp_meta_tag

app/views/layouts/_rendering_tags.html.slim
= stylesheet_pack_tag 'application'
= javascript_pack_tag 'application'

app/views/layouts/_shim.html.slim
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.slim
doctype html
html lang="ja"
  head
    = favicon_pack_tag('smar_logo.ico')
    title
      = full_title(yield(:title))
    = render 'layouts/rails_default'
    = render 'layouts/shim'
    - if Rails.env.production?
      = render 'layouts/google_analytics'
  body
    = render 'layouts/header'
    - flash.each do |message_type, message|
      = content_tag :div, message, class: "alert alert-#{message_type}"
    = render 'layouts/rendering_tags'
    = yield